name: pipeline
on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - name: build
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo $SUPER_SECRET | docker login ghcr.io --username belal67  --password-stdin 
          echo $env:SUPER_SECRET
          docker pull ghcr.io/belal67/hello

