name: pipeline
on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - name: build
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo ${{ secrets.SuperSecret }}
          

