name: pipeline
on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          docker login --username belal67 --password ${{ secrets.PASSWORD }}  ghcr.io
          docker pull ghcr.io/belal67/hello

